# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9845954c0ed9dd80f2c43b8ed4dbb7de54fea200763a88e33e85990a8d8a5b177cff2de1c219bc4029a168a3326a2b3ca3835c6998a64dc94462cb041747e86

test:
  secret_key_base: 947b76f178afb3051510d201bcf6b58bca8af2cd16d6ad92510424822d756bd5bbd53787fb0b0fabcc69c26a1ef6501f577acb83dcdf397d503fb1d518972249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
